name: Build and push the image

on:
  push:
    branches:
      - release

jobs:
  build-publish-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: actions/checkout@v1
      - name: Build and Push to DockerHub
        shell: bash
        run: ./build_and_push.sh
